services:
  app:
    build: .
    container_name: streamlit_app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=Stress
      - DB_USER=postgres
      - DB_PASSWORD=alimov
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: Stress
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alimov
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: